### ISSUE TITLE
login as Election Commission authority 

### ISSUE THREAD

**Issue by Siddhanth-Kivade** [yashtailor/OnlineVotingSystem#1]
we cannot login as Election commission authority, i am using this application for my college project, we can register/login successfully as voter and election candidate but how to login as authority member to create elections ?

**Comment by yashtailor** [comment]
>  we cannot login as Election commission authority, i am using this application for my college project, we can register/login successfully as voter and election candidate but how to login as authority member to create elections ?

ECA has fix credentials. Password is eca123.

**Comment by Sid0006** [comment]
hello sir,
I'm a beginner in android development and thank you for your time for
helping me, but i still cannot login as ECA i tried with many email
id's and password as eca123 and still can't login, I'd be grateful  if
you'd help me out.

**Comment by Siddhanth-Kivade** [comment]
hello sir,
I'm a beginner in android development and thank you for your time for helping me, but i still cannot login as ECA i tried with many email id's and password as eca123 and still can't login, I'd be grateful if you'd help me out.

**Comment by yashtailor** [comment]
> hello sir, I'm a beginner in android development and thank you for your time for helping me, but i still cannot login as ECA i tried with many email id's and password as eca123 and still can't login, I'd be grateful if you'd help me out.

email id is eca@gov.in and password is eca123

**Comment by Bharani-2003** [comment]
hello sir , i have strucked in election page. once after i select the radio button . its not showing  notification as (candidate selected). not even updating in the result page. can you help me out?

**Comment by yashtailor** [comment]
The email id is ***@***.***

Yash Tailor

**Comment by Bharani-2003** [comment]
in electioin result page . the result is not getting updated

**Comment by Bharani-2003** [comment]
![Screenshot_20230430_202152](https://user-images.githubusercontent.com/119350681/235359731-51f44f2b-4123-4fe3-b6c6-98507e3e29c1.png)

**Comment by Bharani-2003** [comment]
all the values are 0. can you help me
