### ISSUE TITLE
App is crashing when we try to open "Go To Election Page"

### ISSUE THREAD

**Issue by Siddhanth-Kivade** [yashtailor/OnlineVotingSystem#2]
after creating elections in ECA and logging in as voter election page is not opening and  same for result page. we are using this as college project it'd be grateful if you could fix this or tell me what I'm doing wrong

**Comment by Bharani-2003** [comment]
hello . after creating elections in ECA and logging in as voter election page is not opening and same for result page. 

even i have same issue . can you help me to fix it

**Comment by yashtailor** [comment]
I cleaned the db, had some noise. It's good to work with.
